/* Generated By:JJTree: Do not edit this line. ASTExpression1.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpression1 extends SimpleNode {
  public ASTExpression1(int id) {
    super(id);
  }

  public ASTExpression1(Fac p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d56f361922d40db68a665b161897a1f1 (do not edit this line) */
