/* Generated By:JJTree: Do not edit this line. ASTerror_skipto.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTerror_skipto extends SimpleNode {
  public ASTerror_skipto(int id) {
    super(id);
  }

  public ASTerror_skipto(Fac p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=22ef39374e69bcc6b88d853f6cb9b173 (do not edit this line) */
