/* Generated By:JJTree: Do not edit this line. ASTMethodReturn.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMethodReturn extends SimpleNode {
  public ASTMethodReturn(int id) {
    super(id);
  }

  public ASTMethodReturn(Fac p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=859f480623f202bc0c35b271e2f7a14b (do not edit this line) */
