/* Generated By:JJTree: Do not edit this line. ASTMethodReturn.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMethodReturn extends SimpleNode {
  public ASTMethodReturn(int id) {
    super(id);
  }

  public ASTMethodReturn(Fac p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=be332ffa09052fac57d1704c5b4bd4dc (do not edit this line) */
