/* Generated By:JJTree: Do not edit this line. ASTMethodBody.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMethodBody extends SimpleNode {
  public ASTMethodBody(int id) {
    super(id);
  }

  public ASTMethodBody(Fac p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dd1eef7b871c1816ec59ceb3226ca503 (do not edit this line) */
