/* Generated By:JJTree: Do not edit this line. ASTType.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTType extends SimpleNode {
  public ASTType(int id) {
    super(id);
  }

  public ASTType(Fac p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c5ea9ffbbbb56d16d70564d86ace4dac (do not edit this line) */
