/* Generated By:JJTree: Do not edit this line. ASTVarDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVarDeclaration extends SimpleNode {
  protected String identifier = "";

  public ASTVarDeclaration(int id) {
    super(id);
  }

  public ASTVarDeclaration(Fac p, int id) {
    super(p, id);
  }

  public String toString() {
    Node type = this.jjtGetChild(0);
    if(type instanceof ASTType) {
  	  return "Variable Declaration : " + ((ASTType)type).getDataType() + " " + this.identifier;
    } else {
      // TODO throw
      return "error";
    }
  }
}
/* JavaCC - OriginalChecksum=4f9d28789843add7285899d7229c7afa (do not edit this line) */
