/* Generated By:JJTree: Do not edit this line. ASTWhileBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTWhileBody extends SimpleNode {
  public ASTWhileBody(int id) {
    super(id);
  }

  public ASTWhileBody(Fac p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e021ce483c3b5b95abe299b3b7c67c71 (do not edit this line) */
