/* Generated By:JJTree: Do not edit this line. ASTWhile.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTWhile extends SimpleNode {
  public ASTWhile(int id) {
    super(id);
  }

  public ASTWhile(Fac p, int id) {
    super(p, id);
  }
  
  public String toString() {
  	return "While";
  }
}
/* JavaCC - OriginalChecksum=dc90cf2295fcc09b3bbc96e7449a40ed (do not edit this line) */
