/* Generated By:JJTree: Do not edit this line. ASTWhileCondition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTWhileCondition extends SimpleNode {
  public ASTWhileCondition(int id) {
    super(id);
  }

  public ASTWhileCondition(Fac p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a3a7becc4527a55b5bca7cee884757d5 (do not edit this line) */
