/* Generated By:JJTree: Do not edit this line. ASTWhileBody.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTWhileBody extends SimpleNode {
  public ASTWhileBody(int id) {
    super(id);
  }

  public ASTWhileBody(Fac p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9207704026b6122a1a4b97b5efc17056 (do not edit this line) */
