/* Generated By:JJTree&JavaCC: Do not edit this line. FacConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FacConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int STATIC = 6;
  /** RegularExpression Id. */
  int VOID = 7;
  /** RegularExpression Id. */
  int PUBLIC = 8;
  /** RegularExpression Id. */
  int CLASS = 9;
  /** RegularExpression Id. */
  int STRING = 10;
  /** RegularExpression Id. */
  int IF = 11;
  /** RegularExpression Id. */
  int ELSE = 12;
  /** RegularExpression Id. */
  int WHILE = 13;
  /** RegularExpression Id. */
  int RETURN = 14;
  /** RegularExpression Id. */
  int INT = 15;
  /** RegularExpression Id. */
  int BOOLEAN = 16;
  /** RegularExpression Id. */
  int PVIRG = 17;
  /** RegularExpression Id. */
  int VIRG = 18;
  /** RegularExpression Id. */
  int SUM = 19;
  /** RegularExpression Id. */
  int SUB = 20;
  /** RegularExpression Id. */
  int MULT = 21;
  /** RegularExpression Id. */
  int DIV = 22;
  /** RegularExpression Id. */
  int EQUAL = 23;
  /** RegularExpression Id. */
  int OPEN_CURLY_BRACKET = 24;
  /** RegularExpression Id. */
  int CLOSE_CURLY_BRACKET = 25;
  /** RegularExpression Id. */
  int OPEN_PARENTHESES = 26;
  /** RegularExpression Id. */
  int CLOSE_PARENTHESES = 27;
  /** RegularExpression Id. */
  int OPEN_BRACKET = 28;
  /** RegularExpression Id. */
  int CLOSE_BRACKET = 29;
  /** RegularExpression Id. */
  int NEW = 30;
  /** RegularExpression Id. */
  int THIS = 31;
  /** RegularExpression Id. */
  int TRUE = 32;
  /** RegularExpression Id. */
  int FALSE = 33;
  /** RegularExpression Id. */
  int LENGTH = 34;
  /** RegularExpression Id. */
  int EXTENDS = 35;
  /** RegularExpression Id. */
  int NOT = 36;
  /** RegularExpression Id. */
  int AND = 37;
  /** RegularExpression Id. */
  int LESS = 38;
  /** RegularExpression Id. */
  int GREATER = 39;
  /** RegularExpression Id. */
  int DOT = 40;
  /** RegularExpression Id. */
  int INTEGERLITERAL = 41;
  /** RegularExpression Id. */
  int IDENTIFIER = 42;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"main\"",
    "\"static\"",
    "\"void\"",
    "\"public\"",
    "\"class\"",
    "\"String\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"return\"",
    "\"int\"",
    "\"boolean\"",
    "\";\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"new\"",
    "\"this\"",
    "\"true\"",
    "\"false\"",
    "\"length\"",
    "\"extends\"",
    "\"!\"",
    "\"&&\"",
    "\"<\"",
    "\">\"",
    "\".\"",
    "<INTEGERLITERAL>",
    "<IDENTIFIER>",
  };

}
