/* Generated By:JavaCC: Do not edit this line. FacTreeConstants.java Version 6.0_1 */
public interface FacTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTCLASSDECLARATION = 1;
  public int JJTVARDECLARATION = 2;
  public int JJTMAINDECLARATION = 3;
  public int JJTMETHODDECLARATION = 4;
  public int JJTVOID = 5;
  public int JJTTYPE = 6;
  public int JJTSTATEMENT = 7;
  public int JJTWHILE = 8;
  public int JJTWHILECONDITION = 9;
  public int JJTWHILEBODY = 10;
  public int JJTEXPRESSION = 11;


  public String[] jjtNodeName = {
    "Program",
    "ClassDeclaration",
    "VarDeclaration",
    "MainDeclaration",
    "MethodDeclaration",
    "void",
    "Type",
    "Statement",
    "While",
    "WhileCondition",
    "WhileBody",
    "Expression",
  };
}
/* JavaCC - OriginalChecksum=c7bd52a9478c86def5b8abd8f39af381 (do not edit this line) */
