/* Generated By:JavaCC: Do not edit this line. FacTreeConstants.java Version 6.0_1 */
public interface FacTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTCLASSDECLARATION = 1;
  public int JJTVARDECLARATION = 2;
  public int JJTMAINDECLARATION = 3;
  public int JJTMETHODDECLARATION = 4;
  public int JJTMETHODPARAMETER = 5;
  public int JJTMETHODBODY = 6;
  public int JJTMETHODRETURN = 7;
  public int JJTTYPE = 8;
  public int JJTSTATEMENT = 9;
  public int JJTVOID = 10;
  public int JJTWHILE = 11;
  public int JJTWHILECONDITION = 12;
  public int JJTWHILEBODY = 13;
  public int JJTEXPRESSION = 14;


  public String[] jjtNodeName = {
    "Program",
    "ClassDeclaration",
    "VarDeclaration",
    "MainDeclaration",
    "MethodDeclaration",
    "MethodParameter",
    "MethodBody",
    "MethodReturn",
    "Type",
    "Statement",
    "void",
    "While",
    "WhileCondition",
    "WhileBody",
    "Expression",
  };
}
/* JavaCC - OriginalChecksum=04a9a5abbddabae6c64117089613c330 (do not edit this line) */
