/* Generated By:JJTree: Do not edit this line. ASTAdd.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTAdd extends SimpleNode {
  public ASTAdd(int id) {
    super(id);
  }

  public ASTAdd(Fac p, int id) {
    super(p, id);
  }
  @Override
  public String toString() {
  	return "+";
  }
}
/* JavaCC - OriginalChecksum=f6774ff78e2d684e75b62073900fd9c4 (do not edit this line) */
