/* Generated By:JJTree: Do not edit this line. ASTAnd.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTAnd extends SimpleNode {
  public ASTAnd(int id) {
    super(id);
  }

  public ASTAnd(Fac p, int id) {
    super(p, id);
  }
  @Override
  public String toString() {
  	return "&&";
  }
}
/* JavaCC - OriginalChecksum=e20336fa0b730b03df09ce0b7fdbc14f (do not edit this line) */
