/* Generated By:JJTree: Do not edit this line. ASTcontains.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTcontains extends SimpleNode {
  public ASTcontains(int id) {
    super(id);
  }

  public ASTcontains(Fac p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f84220729530acc00cd01cfd4e07a37b (do not edit this line) */
