/* Generated By:JJTree: Do not edit this line. ASTcontains.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTcontains extends SimpleNode {
  public ASTcontains(int id) {
    super(id);
  }

  public ASTcontains(Fac p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4dcb8db403c93dca85a8f40db8744032 (do not edit this line) */
