/* Generated By:JJTree: Do not edit this line. ASTcontains.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTcontains extends SimpleNode {
  public ASTcontains(int id) {
    super(id);
  }

  public ASTcontains(Fac p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=360668cd7ab1ddd5c61d56fa30f60809 (do not edit this line) */
