/* Generated By:JJTree: Do not edit this line. ASTDiv.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDiv extends SimpleNode {
  public ASTDiv(int id) {
    super(id);
  }

  public ASTDiv(Fac p, int id) {
    super(p, id);
  }
  @Override
  public String toString() {
  	return "/";
  }
}
/* JavaCC - OriginalChecksum=4ce3924b5e28ecf5cc99d659fcfffbc8 (do not edit this line) */
