/* Generated By:JJTree: Do not edit this line. ASTDot.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDot extends SimpleNode {
  public ASTDot(int id) {
    super(id);
  }

  public ASTDot(Fac p, int id) {
    super(p, id);
  }

  @Override
  public String toString() {
    return ".";
  }
}
/* JavaCC - OriginalChecksum=5a17ba82a38ada2b518d19e6e2cee616 (do not edit this line) */
