/* Generated By:JJTree: Do not edit this line. ASTExpression3.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTExpression3 extends SimpleNode {
  public ASTExpression3(int id) {
    super(id);
  }

  public ASTExpression3(Fac p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b89f299392e39a610859e2201adcca47 (do not edit this line) */
