/* Generated By:JJTree: Do not edit this line. ASTExpression2.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpression2 extends SimpleNode {
  public ASTExpression2(int id) {
    super(id);
  }

  public ASTExpression2(Fac p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ba58c18b52919e3d0a0ef46ab8b1a93c (do not edit this line) */
