/* Generated By:JJTree: Do not edit this line. ASTExpression3.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpression3 extends SimpleNode {
  public ASTExpression3(int id) {
    super(id);
  }

  public ASTExpression3(Fac p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ef65c9f29d389267a9ca95be61a23d34 (do not edit this line) */
