/* Generated By:JJTree: Do not edit this line. ASTExpression1.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpression1 extends SimpleNode {
  public ASTExpression1(int id) {
    super(id);
  }

  public ASTExpression1(Fac p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5c3b9e18d580b2d5fe593eae18c1ad1f (do not edit this line) */
