/* Generated By:JJTree: Do not edit this line. ASTElseBody.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTElseBody extends SimpleNode {
  public ASTElseBody(int id) {
    super(id);
  }

  public ASTElseBody(Fac p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a90e0815a4a4693412c82a9a516b42b9 (do not edit this line) */
