/* Generated By:JJTree: Do not edit this line. ASTElseBody.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTElseBody extends SimpleNode {
  public ASTElseBody(int id) {
    super(id);
  }

  public ASTElseBody(Fac p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b6af6a130faa4c87aaa0687c7e76a8c8 (do not edit this line) */
