/* Generated By:JJTree: Do not edit this line. ASTElseBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTElseBody extends SimpleNode {
  public ASTElseBody(int id) {
    super(id);
  }

  public ASTElseBody(Fac p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bb13830ab2239ffab6e029618c9f5574 (do not edit this line) */
