/* Generated By:JJTree: Do not edit this line. ASTEqual.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTEqual extends SimpleNode {
  public ASTEqual(int id) {
    super(id);
  }

  public ASTEqual(Fac p, int id) {
    super(p, id);
  }
  @Override
  public String toString() {
  	return "=";
  }
}
/* JavaCC - OriginalChecksum=460b094bcc3c3e170fbbf6a519b9a371 (do not edit this line) */
