/* Generated By:JJTree: Do not edit this line. ASTIfCondition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIfCondition extends SimpleNode {
  public ASTIfCondition(int id) {
    super(id);
  }

  public ASTIfCondition(Fac p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5b9970a3f3b8b3e65a3144c9a479ac29 (do not edit this line) */
