/* Generated By:JJTree: Do not edit this line. ASTIfCondition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTIfCondition extends SimpleNode {
  public ASTIfCondition(int id) {
    super(id);
  }

  public ASTIfCondition(Fac p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=39452417dcf4dcaef2648d9634b44b56 (do not edit this line) */
