/* Generated By:JJTree: Do not edit this line. ASTIfBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTIfBody extends SimpleNode {
  public ASTIfBody(int id) {
    super(id);
  }

  public ASTIfBody(Fac p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ba9cae43d3333dc8af0f0fc65df10d90 (do not edit this line) */
