/* Generated By:JJTree: Do not edit this line. ASTMult.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTMult extends SimpleNode {
  public ASTMult(int id) {
    super(id);
    this.op = MyConstants.MUL;
  }

  public ASTMult(Fac p, int id) {
    super(p, id);
  }

  @Override
  public String toString() {
  	return "*";
  }
}
/* JavaCC - OriginalChecksum=3c048f1b381e849abeb3400185dfd9e3 (do not edit this line) */
