/* Generated By:JJTree: Do not edit this line. ASTMethodDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTMethodDeclaration extends SimpleNode {
  protected String identifier="";
  
  public ASTMethodDeclaration(int id) {
    super(id);
  }

  public ASTMethodDeclaration(Fac p, int id) {
    super(p, id);
  }

  @Override
  public String toString() {
    ASTType returnType = (ASTType) this.jjtGetChild(0);
    return "Method declaration : " + returnType.getDataType() + " " + this.identifier + "()";
  }

}
/* JavaCC - OriginalChecksum=4912f1b196fd7ee9c2f16f68305c40c7 (do not edit this line) */
