/* Generated By:JJTree: Do not edit this line. ASTMethodBody.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTMethodBody extends SimpleNode {
  public ASTMethodBody(int id) {
    super(id);
  }

  public ASTMethodBody(Fac p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=eec73f871e5a6f7659ecc745182bc08f (do not edit this line) */
