/* Generated By:JJTree: Do not edit this line. ASTMethodParameter.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTMethodParameter extends SimpleNode {
  protected String identifier = "";
  
  public ASTMethodParameter(int id) {
    super(id);
  }

  public ASTMethodParameter(Fac p, int id) {
    super(p, id);
  }
 
  @Override 
  public String toString() {
    Node type = this.jjtGetChild(0);
    if(type instanceof ASTType) {
  	  return "Parameter : " + ((ASTType)type).getDataType() + " " + this.identifier;
    } else {
      return "error";
    }
  }
  
}
/* JavaCC - OriginalChecksum=ff28215f6dc9da69d12f9b1da5924470 (do not edit this line) */
