/* Generated By:JJTree: Do not edit this line. ASTMethodBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTMethodBody extends SimpleNode {
  public ASTMethodBody(int id) {
    super(id);
  }

  public ASTMethodBody(Fac p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a674df02862996afaacac55c73fa6eae (do not edit this line) */
