/* Generated By:JJTree: Do not edit this line. ASTMethodParameters.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMethodParameters extends SimpleNode {
  public ASTMethodParameters(int id) {
    super(id);
  }

  public ASTMethodParameters(Fac p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=40573bfa188ca19f7272d15360008744 (do not edit this line) */
