/* Generated By:JJTree: Do not edit this line. ASTMethodReturn.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTMethodReturn extends SimpleNode {
  public ASTMethodReturn(int id) {
    super(id);
  }

  public ASTMethodReturn(Fac p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0ee617b6ef1b2956e62201828880b9f9 (do not edit this line) */
