/* Generated By:JJTree: Do not edit this line. ASTNew.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTNew extends SimpleNode {
  public ASTNew(int id) {
    super(id);
  }

  public ASTNew(Fac p, int id) {
    super(p, id);
  }
  @Override
  public String toString() {
  	return "new";
  }
}
/* JavaCC - OriginalChecksum=c6486655ca7c401987bdb20071a4686e (do not edit this line) */
