/* Generated By:JJTree: Do not edit this line. ASTParenteses.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTParenteses extends SimpleNode {
  public ASTParenteses(int id) {
    super(id);
  }

  public ASTParenteses(Fac p, int id) {
    super(p, id);
  }

  @Override
  public String toString() {
    return "()";
  }
}
/* JavaCC - OriginalChecksum=d922c7849dae43d373bef21e5bc1f48e (do not edit this line) */
