/* Generated By:JJTree: Do not edit this line. ASTSub.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTSub extends SimpleNode {
  public ASTSub(int id) {
    super(id);
    this.op = MyConstants.SUB;
  }

  public ASTSub(Fac p, int id) {
    super(p, id);
  }
  @Override
  public String toString() {
  	return "-";
  }
}
/* JavaCC - OriginalChecksum=ff8a80ed77a8f0a6a5043c60d7e19c2a (do not edit this line) */
