/* Generated By:JJTree: Do not edit this line. ASTType.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTType extends SimpleNode {
  /**
   * @brief The Type name (e.g Int, Boolean, or User-defined types)
   */
  protected String dataType = ""; 
  /**
   * @brief Flag telling wether the this type is an array or not
   */
  public Boolean isArray = false;

  public ASTType(int id) {
    super(id);
  }

  public ASTType(Fac p, int id) {
    super(p, id);
  }
  
  /**
   * @brief Returns the data type string
   */
  public String getDataType() {
  	return this.dataType + (this.isArray ? "[]" : "");
  }

  // @Override
  // public String toString() {
  //   return "Type:" + getDataType();
  // }
}
/* JavaCC - OriginalChecksum=c5ea9ffbbbb56d16d70564d86ace4dac (do not edit this line) */
