/* Generated By:JJTree: Do not edit this line. ASTTerm.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTerm extends SimpleNode {
  public ASTTerm(int id) {
    super(id);
  }

  public ASTTerm(Fac p, int id) {
    super(p, id);
  }

  @Override
  public String toString() {
  	return "";
  }
}
/* JavaCC - OriginalChecksum=6f384f9dc4d849455491b9432dbabf6e (do not edit this line) */
