/* Generated By:JJTree: Do not edit this line. ASTWhileCondition.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTWhileCondition extends SimpleNode {
  public ASTWhileCondition(int id) {
    super(id);
  }

  public ASTWhileCondition(Fac p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=69769b350a19c6df30655f056f8c4f95 (do not edit this line) */
