/* Generated By:JJTree: Do not edit this line. ASTWhileBody.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTWhileBody extends SimpleNode {
  public ASTWhileBody(int id) {
    super(id);
  }

  public ASTWhileBody(Fac p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ecf9b7beca2b78916cf9fef79dae42eb (do not edit this line) */
