/* Generated By:JJTree: Do not edit this line. ASTWhileCondition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTWhileCondition extends SimpleNode {
  public ASTWhileCondition(int id) {
    super(id);
  }

  public ASTWhileCondition(Fac p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3c670833a8b607bbac75ed2304c9301e (do not edit this line) */
