/* Generated By:JJTree: Do not edit this line. ASTWhileBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTWhileBody extends SimpleNode {
  public ASTWhileBody(int id) {
    super(id);
  }

  public ASTWhileBody(Fac p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3e52f023501d76c99ec78750735b98ce (do not edit this line) */
