/* Generated By:JavaCC: Do not edit this line. FacTreeConstants.java Version 6.0_1 */
public interface FacTreeConstants
{
  public int JJTERROR_SKIPTO = 0;
  public int JJTPROGRAM = 1;
  public int JJTCLASSDECLARATION = 2;
  public int JJTVARDECLARATION = 3;
  public int JJTMAINDECLARATION = 4;
  public int JJTMETHODDECLARATION = 5;
  public int JJTMETHODPARAMETER = 6;
  public int JJTMETHODBODY = 7;
  public int JJTMETHODRETURN = 8;
  public int JJTTYPE = 9;
  public int JJTVOID = 10;
  public int JJTEQUAL = 11;
  public int JJTIF = 12;
  public int JJTIFCONDITION = 13;
  public int JJTIFBODY = 14;
  public int JJTELSEBODY = 15;
  public int JJTWHILE = 16;
  public int JJTWHILECONDITION = 17;
  public int JJTWHILEBODY = 18;
  public int JJTAND = 19;
  public int JJTLESS = 20;
  public int JJTADD = 21;
  public int JJTSUB = 22;
  public int JJTMULT = 23;
  public int JJTDIV = 24;
  public int JJTTERM = 25;


  public String[] jjtNodeName = {
    "error_skipto",
    "Program",
    "ClassDeclaration",
    "VarDeclaration",
    "MainDeclaration",
    "MethodDeclaration",
    "MethodParameter",
    "MethodBody",
    "MethodReturn",
    "Type",
    "void",
    "Equal",
    "If",
    "IfCondition",
    "IfBody",
    "ElseBody",
    "While",
    "WhileCondition",
    "WhileBody",
    "And",
    "Less",
    "Add",
    "Sub",
    "Mult",
    "Div",
    "Term",
  };
}
/* JavaCC - OriginalChecksum=4fb81a74603efce53cc50181ff50d332 (do not edit this line) */
