/* Generated By:JavaCC: Do not edit this line. FacTreeConstants.java Version 5.0 */
public interface FacTreeConstants
{
  public int JJTCONTAINS = 0;
  public int JJTERROR_SKIPTO = 1;
  public int JJTPROGRAM = 2;
  public int JJTCLASSDECLARATION = 3;
  public int JJTVARDECLARATION = 4;
  public int JJTMAINDECLARATION = 5;
  public int JJTMETHODDECLARATION = 6;
  public int JJTMETHODPARAMETER = 7;
  public int JJTMETHODBODY = 8;
  public int JJTMETHODRETURN = 9;
  public int JJTTYPE = 10;
  public int JJTVOID = 11;
  public int JJTEQUAL = 12;
  public int JJTIF = 13;
  public int JJTIFCONDITION = 14;
  public int JJTIFBODY = 15;
  public int JJTELSEBODY = 16;
  public int JJTWHILE = 17;
  public int JJTWHILECONDITION = 18;
  public int JJTWHILEBODY = 19;
  public int JJTEXPRESSION = 20;
  public int JJTAND = 21;
  public int JJTPARENTESES = 22;
  public int JJTDOT = 23;
  public int JJTLESS = 24;
  public int JJTADD = 25;
  public int JJTSUB = 26;
  public int JJTMULT = 27;
  public int JJTDIV = 28;
  public int JJTTERM = 29;
  public int JJTNEW = 30;


  public String[] jjtNodeName = {
    "contains",
    "error_skipto",
    "Program",
    "ClassDeclaration",
    "VarDeclaration",
    "MainDeclaration",
    "MethodDeclaration",
    "MethodParameter",
    "MethodBody",
    "MethodReturn",
    "Type",
    "void",
    "Equal",
    "If",
    "IfCondition",
    "IfBody",
    "ElseBody",
    "While",
    "WhileCondition",
    "WhileBody",
    "Expression",
    "And",
    "Parenteses",
    "Dot",
    "Less",
    "Add",
    "Sub",
    "Mult",
    "Div",
    "Term",
    "New",
  };
}
/* JavaCC - OriginalChecksum=32416ab72a33b5091a6cfe9fbdbd7946 (do not edit this line) */
